# Generated by Django 4.0.1 on 2022-07-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carssamenvatiing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarsSamenvatiing',
            new_name='CarsSamenvating',
        ),
    ]
