# Generated by Django 4.0.1 on 2022-09-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_muziek_album_muziek_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='muziekAfbeelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumNaam', models.CharField(max_length=200, null=True)),
                ('CarsAfbeeldingAlbum', models.FileField(null=True, upload_to='uploads/muziek/afbeelding/cover/')),
                ('CarsFilm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carsfilms')),
            ],
        ),
    ]
