# Generated by Django 4.0.1 on 2022-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_carspersonages_linkscarssites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carspersonages',
            old_name='linksCarsSites',
            new_name='linksCarsSite1',
        ),
        migrations.AddField(
            model_name='carspersonages',
            name='linksCarsSite2',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
