# Generated by Django 4.0.1 on 2022-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarsFilm_Naam', models.CharField(max_length=200)),
                ('CarsTrailer', models.FileField(upload_to='uploads/')),
                ('CarsDescription', models.CharField(max_length=200)),
                ('CarsPersonages', models.CharField(max_length=200)),
            ],
        ),
    ]
