# Generated by Django 4.0.1 on 2022-07-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsfilms',
            name='CarsPersonages',
        ),
        migrations.AlterField(
            model_name='carsfilms',
            name='CarsTrailer',
            field=models.FileField(upload_to='uploads/Trailer/'),
        ),
        migrations.CreateModel(
            name='CarsPersonages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarsPersonage_Naam', models.CharField(max_length=200)),
                ('CarsAfbeelding', models.FileField(upload_to='uploads/Afbeelding/')),
                ('CarsPersonageDescription', models.CharField(max_length=200)),
                ('carsfilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carsfilms')),
            ],
        ),
    ]
