# Generated by Django 4.0.1 on 2022-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_carsfilms_carspersonages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsfilms',
            name='CarsDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carspersonages',
            name='CarsPersonageDescription',
            field=models.TextField(),
        ),
    ]
