# Generated by Django 4.0.1 on 2022-07-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carsfilms_carsdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspersonages',
            name='CarsAfbeelding',
        ),
        migrations.AddField(
            model_name='carsfilms',
            name='CarsFilm_Afbeelding',
            field=models.FileField(null=True, upload_to='uploads/film/Afbeelding/'),
        ),
        migrations.AddField(
            model_name='carspersonages',
            name='CarsPersonnage_Afbeelding',
            field=models.FileField(null=True, upload_to='uploads/personnage/Afbeelding/'),
        ),
        migrations.AlterField(
            model_name='carspersonages',
            name='CarsPersonageDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carspersonages',
            name='CarsPersonage_Naam',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspersonages',
            name='carsfilm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carsfilms'),
        ),
    ]
