# Generated by Django 4.0.1 on 2022-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_carspersonages_carsafbeelding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsfilms',
            name='CarsIntro',
            field=models.TextField(null=True),
        ),
    ]
