# Generated by Django 4.0.1 on 2022-07-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carsfilms_carsintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsSamenvatiing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SamenvattingTitle', models.CharField(max_length=200, null=True)),
                ('SamenvatingDescriptie', models.TextField(null=True)),
                ('CarsFilm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carsfilms')),
            ],
        ),
    ]
