# Generated by Django 4.0.1 on 2022-07-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_carssamenvatiing_carssamenvating'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewsFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField(null=True)),
                ('CarsFilm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carsfilms')),
            ],
        ),
    ]
