# Generated by Django 4.0.6 on 2022-08-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_reviewsfilms'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspersonages',
            name='CarsPersonageIntro',
            field=models.TextField(null=True),
        ),
    ]
