# Generated by Django 4.0.1 on 2022-08-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carspersonages_carspersonageintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='muziek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MuziekNaam', models.CharField(max_length=200, null=True)),
                ('MuziekAfbeelding', models.FileField(null=True, upload_to='uploads/muziek/afbeelding/')),
                ('MuziekBestand', models.FileField(null=True, upload_to='uploads/muziek/muziek/')),
                ('CarsFilm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carsfilms')),
            ],
        ),
    ]
