# Generated by Django 4.0.1 on 2022-08-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_muziek'),
    ]

    operations = [
        migrations.AddField(
            model_name='muziek',
            name='album',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='muziek',
            name='artist',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
